#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

banner "DSH Bridge：配置 R2 自动发布所需密钥"

# ── Stage 1：gh 预检 ──────────────────────────────────────────────────────
stage "预检：GitHub CLI"
say "这个向导只做一件事：把构建/发布要用的 9 个值写进 GitHub Actions secrets。"
say "值不会落到仓库文件里；写 secret 需要 gh 已安装并已登录。"
if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
  note "gh 已就绪。"
else
  warn "没有可用的 gh（未安装或未登录）。下面每个 set_secret 都会被跳过并记入结尾清单。"
  step "安装：macOS brew install gh ｜ Debian/Ubuntu sudo apt install gh ｜ 其它见 https://github.com/cli/cli#installation"
  step "登录：gh auth login（选择 GitHub.com，勾选 repo 权限即可）"
  pause "装好并登录后按 Enter 继续"
fi

# ── Stage 2：R2 S3 令牌 ────────────────────────────────────────────────────
stage "Cloudflare R2：创建 S3 API 令牌"
say "GitHub Actions 里的 aws s3 cp 用这对密钥上传安装包。"
open_url "https://dash.cloudflare.com/?to=/:account/r2/api-tokens"
step "点 Create API token（或 Manage API Tokens → Create API token）。"
step "权限选 Object Read & Write；Bucket 选放安装包的那个桶（建议只授权这一个桶）。"
step "创建后立刻显示 Access Key ID 与 Secret Access Key——Secret 只显示一次，务必当场复制。"
ask_secret R2_ACCESS_KEY_ID "粘贴 Access Key ID："
ask_secret R2_SECRET_ACCESS_KEY "粘贴 Secret Access Key："
set_secret R2_ACCESS_KEY_ID "$R2_ACCESS_KEY_ID"
set_secret R2_SECRET_ACCESS_KEY "$R2_SECRET_ACCESS_KEY"

# ── Stage 3：S3 端点与桶名 ────────────────────────────────────────────────
stage "Cloudflare R2：S3 端点与桶名"
say "端点形如 https://<ACCOUNT_ID>.r2.cloudflarestorage.com，是上传用的接口，不是下载地址。"
open_url "https://dash.cloudflare.com/?to=/:account/r2"
step "在 R2 Overview 右侧找到 Account ID；桶页 Settings 里也能看到 S3 API endpoint。"
step "端点整串粘贴（含 https://，结尾不要带斜杠）。"
step "桶名就是桶页地址里的名字。"
ask R2_ENDPOINT "S3 endpoint："
ask R2_BUCKET "Bucket 名称："
set_secret R2_ENDPOINT "$R2_ENDPOINT"
set_secret R2_BUCKET "$R2_BUCKET"

# ── Stage 4：公共访问 ─────────────────────────────────────────────────────
stage "Cloudflare R2：开启公共访问"
say "App 与浏览器都要能匿名下载，桶必须可公开读取。"
open_url "https://dash.cloudflare.com/?to=/:account/r2"
step "进入桶 → Settings → Public access。"
step "测试用：把 R2.dev subdomain 设为 Allow，复制 https://pub-xxxx.r2.dev。"
step "正式用：Connect Custom Domain 绑定自己的域名（推荐），复制 https://dl.example.com。"
warn "这里填公开下载域名，不要填上一步的 S3 端点；结尾不要带斜杠。"
ask R2_PUBLIC_DOMAIN "公开访问地址（https://...）[https://pub-b275276346ca49b39dbf6f6d65687153.r2.dev]："
[ -n "$R2_PUBLIC_DOMAIN" ] || R2_PUBLIC_DOMAIN="https://pub-b275276346ca49b39dbf6f6d65687153.r2.dev"
set_secret R2_PUBLIC_DOMAIN "$R2_PUBLIC_DOMAIN"

# ── Stage 5：Android 签名密钥 ─────────────────────────────────────────────
stage "Android 签名密钥"
say "CI 必须用和你本地同一个密钥库签名，否则已安装的 App 会因签名不一致拒绝升级。"
if [ -f keystore/dsh-bridge-app.jks ]; then
  note "找到 keystore/dsh-bridge-app.jks。"
else
  warn "没找到 keystore/dsh-bridge-app.jks，请确认密钥库路径后再粘贴 base64。"
fi
step "Linux 生成 base64：base64 -w0 keystore/dsh-bridge-app.jks > /tmp/ks.b64 && cat /tmp/ks.b64"
step "macOS 生成 base64：base64 -i keystore/dsh-bridge-app.jks | tr -d "\n" | pbcopy"
ask_secret ANDROID_KEYSTORE_BASE64 "粘贴 keystore 的 base64（很长，粘贴完回车）："
if ! printf "%s" "$ANDROID_KEYSTORE_BASE64" | base64 -d >/dev/null 2>&1; then
  warn "这段 base64 解码失败，可能没复制完整；仍会写入当前值，建议稍后重跑本阶段。"
fi
ask_secret ANDROID_KEYSTORE_PASSWORD "storePassword："
ask ANDROID_KEY_ALIAS "keyAlias [dsh-bridge-app]："
[ -n "$ANDROID_KEY_ALIAS" ] || ANDROID_KEY_ALIAS="dsh-bridge-app"
ask_secret ANDROID_KEY_PASSWORD "keyPassword（PKCS12 下与 storePassword 相同，直接回车复用）："
[ -n "$ANDROID_KEY_PASSWORD" ] || ANDROID_KEY_PASSWORD="$ANDROID_KEYSTORE_PASSWORD"
set_secret ANDROID_KEYSTORE_BASE64 "$ANDROID_KEYSTORE_BASE64"
set_secret ANDROID_KEYSTORE_PASSWORD "$ANDROID_KEYSTORE_PASSWORD"
set_secret ANDROID_KEY_ALIAS "$ANDROID_KEY_ALIAS"
set_secret ANDROID_KEY_PASSWORD "$ANDROID_KEY_PASSWORD"

# ── Stage 6：发测试版本 ───────────────────────────────────────────────────
stage "发一个测试版本"
say "9 个 secret 配好后，推一个 tag 就会触发构建 + 上传 R2 + 公网校验。"
step "git tag v1.1.6 && git push origin v1.1.6"
step "到仓库 Actions → Build and Release to R2 看是否全绿。"
step "浏览器打开 <你的公开域名>/latest.json，应返回 JSON 且 versionName 与 tag 一致。"
if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
  step "查最近运行：gh run list --workflow=release.yml --limit 5"
fi
pause "完成后按 Enter 结束"

finish
